package ec.edu.espe.inclass.view;

import ec.edu.espe.inclass.controller.CourseController;
import ec.edu.espe.inclass.controller.DataPersistence;
import ec.edu.espe.inclass.controller.FormController;
import java.awt.event.KeyEvent;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;

/**
 *
 * @author alejo
 */
public class FrmAddGrade extends javax.swing.JFrame {

    public FrmAddGrade() {
        initComponents();
        FormController.uploadCourses(this);
        FormController.showTableDate(0, 0, this);
        this.setLocationRelativeTo(this);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cmbGradeType = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        cmbUnit = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        btnRemove = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblGrades = new javax.swing.JTable();
        lblAction = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cmbNrc = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuLogOut = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        menuEnrolled = new javax.swing.JMenuItem();
        menuAddStudent = new javax.swing.JMenuItem();
        menuRemoveStudent = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuManageGrade = new javax.swing.JMenuItem();
        menuGradeRecord = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        menuTakeAttendance = new javax.swing.JMenuItem();
        menuGetAttendace = new javax.swing.JMenuItem();
        menuTutorship = new javax.swing.JMenu();
        menuTutorships = new javax.swing.JMenuItem();
        menuCourses = new javax.swing.JMenu();
        menuManageCourses = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(228, 249, 245));

        jLabel1.setFont(new java.awt.Font("Malgun Gothic", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(64, 81, 78));
        jLabel1.setText("ADD GRADE");

        cmbGradeType.setBackground(new java.awt.Color(17, 153, 158));
        cmbGradeType.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cmbGradeType.setForeground(new java.awt.Color(64, 81, 78));
        cmbGradeType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Homework", "Workshop", "Test", "Exam" }));
        cmbGradeType.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbGradeTypeItemStateChanged(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(64, 81, 78));
        jLabel4.setText("Unit #");

        cmbUnit.setBackground(new java.awt.Color(17, 153, 158));
        cmbUnit.setForeground(new java.awt.Color(64, 81, 78));
        cmbUnit.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3" }));
        cmbUnit.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbUnitItemStateChanged(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(64, 81, 78));
        jLabel5.setText("Grade:");

        btnAdd.setBackground(new java.awt.Color(48, 227, 202));
        btnAdd.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAdd.setForeground(new java.awt.Color(64, 81, 78));
        btnAdd.setText("Add new grade");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnRemove.setBackground(new java.awt.Color(48, 227, 202));
        btnRemove.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnRemove.setForeground(new java.awt.Color(64, 81, 78));
        btnRemove.setText("Remove last grade");
        btnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveActionPerformed(evt);
            }
        });

        btnSave.setBackground(new java.awt.Color(48, 227, 202));
        btnSave.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSave.setForeground(new java.awt.Color(64, 81, 78));
        btnSave.setText("Save grades");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        tblGrades.setBackground(new java.awt.Color(48, 227, 202));
        tblGrades.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        tblGrades.setForeground(new java.awt.Color(0, 0, 0));
        tblGrades.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "#", "ID", "Student", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8", "Title 9", "Title 10", "Title 11", "Title 12", "Title 13", "Title 14", "Title 15"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, true, true, true, true, true, true, true, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblGrades.setAutoResizeMode(0);
        tblGrades.getTableHeader().setReorderingAllowed(false);
        tblGrades.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tblGradesKeyTyped(evt);
            }
        });
        jScrollPane2.setViewportView(tblGrades);
        if (tblGrades.getColumnModel().getColumnCount() > 0) {
            tblGrades.getColumnModel().getColumn(0).setPreferredWidth(30);
            tblGrades.getColumnModel().getColumn(0).setMaxWidth(30);
            tblGrades.getColumnModel().getColumn(1).setPreferredWidth(70);
            tblGrades.getColumnModel().getColumn(1).setMaxWidth(70);
            tblGrades.getColumnModel().getColumn(2).setPreferredWidth(90);
            tblGrades.getColumnModel().getColumn(2).setMaxWidth(90);
        }

        lblAction.setForeground(new java.awt.Color(153, 0, 0));
        lblAction.setText("Grades wasn´t saved, please use numbers and point(.)");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(64, 81, 78));
        jLabel2.setText("Press \"Enter\" before saving");

        cmbNrc.setBackground(new java.awt.Color(17, 153, 158));
        cmbNrc.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cmbNrc.setForeground(new java.awt.Color(64, 81, 78));
        cmbNrc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbNrc.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbNrcItemStateChanged(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(64, 81, 78));
        jLabel8.setText("Select a Course");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblAction, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1))
                            .addComponent(jScrollPane2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnRemove, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2))
                        .addGap(19, 19, 19))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbNrc, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(cmbUnit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cmbGradeType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbNrc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel4)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbUnit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(cmbGradeType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel5))))
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(btnAdd)
                        .addGap(18, 18, 18)
                        .addComponent(btnSave)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addGap(107, 107, 107)
                        .addComponent(btnRemove))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblAction, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(17, 153, 158));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 33, Short.MAX_VALUE)
        );

        menuLogOut.setText("InClass");

        jMenuItem2.setText("Log out");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        menuLogOut.add(jMenuItem2);

        jMenuBar1.add(menuLogOut);

        jMenu3.setText("Students");

        menuEnrolled.setText("Show enrolled students");
        menuEnrolled.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuEnrolledActionPerformed(evt);
            }
        });
        jMenu3.add(menuEnrolled);

        menuAddStudent.setText("Add Student");
        menuAddStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAddStudentActionPerformed(evt);
            }
        });
        jMenu3.add(menuAddStudent);

        menuRemoveStudent.setText("Remove Student");
        menuRemoveStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuRemoveStudentActionPerformed(evt);
            }
        });
        jMenu3.add(menuRemoveStudent);

        jMenuBar1.add(jMenu3);

        jMenu2.setText("Grades");

        menuManageGrade.setText("Manage Grades");
        menuManageGrade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuManageGradeActionPerformed(evt);
            }
        });
        jMenu2.add(menuManageGrade);

        menuGradeRecord.setText("Get grade record");
        menuGradeRecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuGradeRecordActionPerformed(evt);
            }
        });
        jMenu2.add(menuGradeRecord);

        jMenuBar1.add(jMenu2);

        jMenu4.setText("Attendance");

        menuTakeAttendance.setText("TakeAttendance");
        menuTakeAttendance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuTakeAttendanceActionPerformed(evt);
            }
        });
        jMenu4.add(menuTakeAttendance);

        menuGetAttendace.setText("Get attendance record");
        menuGetAttendace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuGetAttendaceActionPerformed(evt);
            }
        });
        jMenu4.add(menuGetAttendace);

        jMenuBar1.add(jMenu4);

        menuTutorship.setText("Tutorships");

        menuTutorships.setText("Get tutorship record");
        menuTutorships.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuTutorshipsActionPerformed(evt);
            }
        });
        menuTutorship.add(menuTutorships);

        jMenuBar1.add(menuTutorship);

        menuCourses.setText("Courses");

        menuManageCourses.setText("Manage courses");
        menuManageCourses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuManageCoursesActionPerformed(evt);
            }
        });
        menuCourses.add(menuManageCourses);

        jMenuBar1.add(menuCourses);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbUnitItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbUnitItemStateChanged
        int unitNumber = cmbUnit.getSelectedIndex();
        int gradeType = cmbGradeType.getSelectedIndex();
        FormController.showTableDate(unitNumber, gradeType, this);
    }//GEN-LAST:event_cmbUnitItemStateChanged

    private void cmbGradeTypeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbGradeTypeItemStateChanged
        int unitNumber = cmbUnit.getSelectedIndex();
        int gradeType = cmbGradeType.getSelectedIndex();
        FormController.showTableDate(unitNumber, gradeType, this);
    }//GEN-LAST:event_cmbGradeTypeItemStateChanged

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        FormController.saveActionGrade(this);

    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        FormController.AddGradeAction(this);
    }//GEN-LAST:event_btnAddActionPerformed


    private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveActionPerformed
        FormController.removeGradeAction(this);
    }//GEN-LAST:event_btnRemoveActionPerformed


    private void tblGradesKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblGradesKeyTyped
        char c = evt.getKeyChar();
        char c1 = (char) 0;
        if (!Character.isDigit(c) && c != KeyEvent.VK_PERIOD && c != KeyEvent.VK_DELETE) {
            evt.setKeyChar(c1);
        }
    }//GEN-LAST:event_tblGradesKeyTyped

    private void cmbNrcItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbNrcItemStateChanged
        DataPersistence dataPersistence;
        dataPersistence = DataPersistence.getInstance();
        int position;
        position = (Integer) cmbNrc.getSelectedIndex();
        dataPersistence.setPosition(position);
        FormController.showTableDate(0, 0, this);
    }//GEN-LAST:event_cmbNrcItemStateChanged

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        FrmInClassMenu frmInClassMenu = new FrmInClassMenu();
        frmInClassMenu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void menuEnrolledActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuEnrolledActionPerformed
        FrmShowEnrolledStudents frmShowEnrolledStudents = new FrmShowEnrolledStudents();
        frmShowEnrolledStudents.setVisible(true);
        FrmShowEnrolledStudents.txtNrcReceive.setText(CourseController.getPositionNrc());
        this.setVisible(false);
    }//GEN-LAST:event_menuEnrolledActionPerformed

    private void menuAddStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAddStudentActionPerformed
        FrmAddStudent frmAddStudent = new FrmAddStudent();
        frmAddStudent.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_menuAddStudentActionPerformed

    private void menuRemoveStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuRemoveStudentActionPerformed
        FrmRemoveStudent frmRemoveStudent = new FrmRemoveStudent();
        frmRemoveStudent.setVisible(true);
        FrmRemoveStudent.txtNrcReceive.setText(CourseController.getPositionNrc());
        this.setVisible(false);
    }//GEN-LAST:event_menuRemoveStudentActionPerformed

    private void menuManageGradeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuManageGradeActionPerformed
        FrmAddGrade frmAddGrade = new FrmAddGrade();
        frmAddGrade.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_menuManageGradeActionPerformed

    private void menuGradeRecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuGradeRecordActionPerformed
        FrmGetGradeRecord frmGetGradeRecord = new FrmGetGradeRecord();
        frmGetGradeRecord.setVisible(true);
        FrmGetGradeRecord.txtNrcReceive.setText(CourseController.getPositionNrc());
        this.setVisible(false);
    }//GEN-LAST:event_menuGradeRecordActionPerformed

    private void menuTakeAttendanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuTakeAttendanceActionPerformed
        FrmTakeAttendance frmTakeAttendance = new FrmTakeAttendance();
        frmTakeAttendance.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_menuTakeAttendanceActionPerformed

    private void menuGetAttendaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuGetAttendaceActionPerformed
        FrmGetAttendanceRecord frmGetAttendanceRecord = new FrmGetAttendanceRecord();
        frmGetAttendanceRecord.setVisible(true);
        FrmGetAttendanceRecord.txtNrcReceive.setText(CourseController.getPositionNrc());
        this.setVisible(false);
    }//GEN-LAST:event_menuGetAttendaceActionPerformed

    private void menuTutorshipsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuTutorshipsActionPerformed
        FrmGetTutorshipRecord frmGetTutorshipRecord = new FrmGetTutorshipRecord();
        frmGetTutorshipRecord.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_menuTutorshipsActionPerformed

    private void menuManageCoursesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuManageCoursesActionPerformed
        FrmTeacherMenu frmTeacherMenu = new FrmTeacherMenu();
        frmTeacherMenu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_menuManageCoursesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmAddGrade().setVisible(true);
            }
        });
    }
    
    public JComboBox<String> getCmbNrc() {
        return cmbNrc;
    }

    public JButton getBtnAdd() {
        return btnAdd;
    }


    public JButton getBtnRemove() {
        return btnRemove;
    }

    public JButton getBtnSave() {
        return btnSave;
    }

    public JComboBox<String> getCmbGradeType() {
        return cmbGradeType;
    }

    public JComboBox<String> getCmbUnit() {
        return cmbUnit;
    }

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public JLabel getjLabel2() {
        return jLabel2;
    }

    public JLabel getjLabel4() {
        return jLabel4;
    }

    public JLabel getjLabel5() {
        return jLabel5;
    }

    public JPanel getjPanel1() {
        return jPanel1;
    }

    public JPanel getjPanel2() {
        return jPanel2;
    }

    public JScrollPane getjScrollPane2() {
        return jScrollPane2;
    }

    public JLabel getLblAction() {
        return lblAction;
    }

    public JTable getTblGrades() {
        return tblGrades;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnRemove;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<String> cmbGradeType;
    private javax.swing.JComboBox<String> cmbNrc;
    private javax.swing.JComboBox<String> cmbUnit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblAction;
    private javax.swing.JMenuItem menuAddStudent;
    private javax.swing.JMenu menuCourses;
    private javax.swing.JMenuItem menuEnrolled;
    private javax.swing.JMenuItem menuGetAttendace;
    private javax.swing.JMenuItem menuGradeRecord;
    private javax.swing.JMenu menuLogOut;
    private javax.swing.JMenuItem menuManageCourses;
    private javax.swing.JMenuItem menuManageGrade;
    private javax.swing.JMenuItem menuRemoveStudent;
    private javax.swing.JMenuItem menuTakeAttendance;
    private javax.swing.JMenu menuTutorship;
    private javax.swing.JMenuItem menuTutorships;
    private javax.swing.JTable tblGrades;
    // End of variables declaration//GEN-END:variables
}
