package ec.edu.espe.inclass.view;

import ec.edu.espe.inclass.controller.CourseController;
import ec.edu.espe.inclass.controller.DataPersistence;

/**
 *
 * @author Alejandro Cuadrado, Developer Bears, DCCO-ESPE
 * @author Alexander Guaman, Developer Bears, DCCO-ESPE
 * @author Sheylee Enriquez, Developer Bears, DCCO-ESPE
 * @author Stephen Drouet, Developer Bears, DCCO-ESPE
 */
public class FrmTeacherMenu extends javax.swing.JFrame {

    public FrmTeacherMenu() {
        initComponents();
        DataPersistence dataPersistence;
        dataPersistence = DataPersistence.getInstance();
        int position = 0;
        dataPersistence.setPosition(position);
        this.setLocationRelativeTo(this);

        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        btnRemove = new javax.swing.JButton();
        btnGet = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuLogOut = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        menuEnrolled = new javax.swing.JMenuItem();
        menuAddStudent = new javax.swing.JMenuItem();
        menuRemoveStudent = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuManageGrade = new javax.swing.JMenuItem();
        menuGradeRecord = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        menuTakeAttendance = new javax.swing.JMenuItem();
        menuGetAttendace = new javax.swing.JMenuItem();
        menuTutorship = new javax.swing.JMenu();
        menuTutorships = new javax.swing.JMenuItem();
        menuCourses = new javax.swing.JMenu();
        menuManageCourses = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(228, 249, 245));

        title.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        title.setForeground(new java.awt.Color(64, 81, 78));
        title.setText("ADMINISTRAR CURSOS");

        btnAdd.setBackground(new java.awt.Color(48, 227, 202));
        btnAdd.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnAdd.setForeground(new java.awt.Color(64, 81, 78));
        btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/add.png"))); // NOI18N
        btnAdd.setText("Agregar Curso");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnRemove.setBackground(new java.awt.Color(48, 227, 202));
        btnRemove.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnRemove.setForeground(new java.awt.Color(64, 81, 78));
        btnRemove.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/delete.png"))); // NOI18N
        btnRemove.setText("Eliminar Curso");
        btnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveActionPerformed(evt);
            }
        });

        btnGet.setBackground(new java.awt.Color(48, 227, 202));
        btnGet.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnGet.setForeground(new java.awt.Color(64, 81, 78));
        btnGet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/get.png"))); // NOI18N
        btnGet.setText("Registro de Tutorias");
        btnGet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnGet)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(54, 54, 54)
                                .addComponent(btnRemove, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(120, 120, 120))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(title)
                        .addGap(198, 198, 198))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(title)
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd)
                    .addComponent(btnRemove))
                .addGap(53, 53, 53)
                .addComponent(btnGet)
                .addContainerGap(110, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(17, 153, 158));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 74, Short.MAX_VALUE)
        );

        menuLogOut.setText("EnClase");

        jMenuItem2.setText("Salir");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        menuLogOut.add(jMenuItem2);

        jMenuBar1.add(menuLogOut);

        jMenu3.setText("Estudiantes");

        menuEnrolled.setText("Registro de Alumnos");
        menuEnrolled.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuEnrolledActionPerformed(evt);
            }
        });
        jMenu3.add(menuEnrolled);

        menuAddStudent.setText("Agregar Alumno");
        menuAddStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAddStudentActionPerformed(evt);
            }
        });
        jMenu3.add(menuAddStudent);

        menuRemoveStudent.setText("Quitar Alumno");
        menuRemoveStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuRemoveStudentActionPerformed(evt);
            }
        });
        jMenu3.add(menuRemoveStudent);

        jMenuBar1.add(jMenu3);

        jMenu2.setText("Notas");

        menuManageGrade.setText("Agregar Nota");
        menuManageGrade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuManageGradeActionPerformed(evt);
            }
        });
        jMenu2.add(menuManageGrade);

        menuGradeRecord.setText("Registro de Notas");
        menuGradeRecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuGradeRecordActionPerformed(evt);
            }
        });
        jMenu2.add(menuGradeRecord);

        jMenuBar1.add(jMenu2);

        jMenu4.setText("Asistencia");

        menuTakeAttendance.setText("Tomar Asistencia");
        menuTakeAttendance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuTakeAttendanceActionPerformed(evt);
            }
        });
        jMenu4.add(menuTakeAttendance);

        menuGetAttendace.setText("Registro de Asistencia");
        menuGetAttendace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuGetAttendaceActionPerformed(evt);
            }
        });
        jMenu4.add(menuGetAttendace);

        jMenuBar1.add(jMenu4);

        menuTutorship.setText("Tutorias");

        menuTutorships.setText("Registro de Tutorias");
        menuTutorships.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuTutorshipsActionPerformed(evt);
            }
        });
        menuTutorship.add(menuTutorships);

        jMenuBar1.add(menuTutorship);

        menuCourses.setText("Cursos");

        menuManageCourses.setText("Administrar Cursos");
        menuManageCourses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuManageCoursesActionPerformed(evt);
            }
        });
        menuCourses.add(menuManageCourses);

        jMenuBar1.add(menuCourses);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        FrmAddCourse frmAddCourse = new FrmAddCourse();
        frmAddCourse.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveActionPerformed
        FrmRemoveCourse frmRemoveCourse = new FrmRemoveCourse();
        frmRemoveCourse.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnRemoveActionPerformed

    private void btnGetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGetActionPerformed
        FrmGetTutorshipRecord frmGetTutorshipRecord = new FrmGetTutorshipRecord();
        frmGetTutorshipRecord.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnGetActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        FrmInClassMenu frmInClassMenu = new FrmInClassMenu();
        frmInClassMenu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void menuEnrolledActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuEnrolledActionPerformed
        FrmShowEnrolledStudents frmShowEnrolledStudents = new FrmShowEnrolledStudents();
        frmShowEnrolledStudents.setVisible(true);
        FrmShowEnrolledStudents.txtNrcReceive.setText(CourseController.getPositionNrc());
        this.setVisible(false);
    }//GEN-LAST:event_menuEnrolledActionPerformed

    private void menuAddStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAddStudentActionPerformed
        FrmAddStudent frmAddStudent = new FrmAddStudent();
        frmAddStudent.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_menuAddStudentActionPerformed

    private void menuRemoveStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuRemoveStudentActionPerformed
        FrmRemoveStudent frmRemoveStudent = new FrmRemoveStudent();
        frmRemoveStudent.setVisible(true);
        FrmRemoveStudent.txtNrcReceive.setText(CourseController.getPositionNrc());
        this.setVisible(false);
    }//GEN-LAST:event_menuRemoveStudentActionPerformed

    private void menuManageGradeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuManageGradeActionPerformed
        FrmAddGrade frmAddGrade = new FrmAddGrade();
        frmAddGrade.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_menuManageGradeActionPerformed

    private void menuGradeRecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuGradeRecordActionPerformed
        FrmGetGradeRecord frmGetGradeRecord = new FrmGetGradeRecord();
        frmGetGradeRecord.setVisible(true);
        FrmGetGradeRecord.txtNrcReceive.setText(CourseController.getPositionNrc());
        this.setVisible(false);
    }//GEN-LAST:event_menuGradeRecordActionPerformed

    private void menuTakeAttendanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuTakeAttendanceActionPerformed
        FrmTakeAttendance frmTakeAttendance = new FrmTakeAttendance();
        frmTakeAttendance.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_menuTakeAttendanceActionPerformed

    private void menuGetAttendaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuGetAttendaceActionPerformed
        FrmGetAttendanceRecord frmGetAttendanceRecord = new FrmGetAttendanceRecord();
        frmGetAttendanceRecord.setVisible(true);
        FrmGetAttendanceRecord.txtNrcReceive.setText(CourseController.getPositionNrc());
        this.setVisible(false);
    }//GEN-LAST:event_menuGetAttendaceActionPerformed

    private void menuTutorshipsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuTutorshipsActionPerformed
        FrmGetTutorshipRecord frmGetTutorshipRecord = new FrmGetTutorshipRecord();
        frmGetTutorshipRecord.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_menuTutorshipsActionPerformed

    private void menuManageCoursesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuManageCoursesActionPerformed
        FrmTeacherMenu frmTeacherMenu = new FrmTeacherMenu();
        frmTeacherMenu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_menuManageCoursesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmTeacherMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmTeacherMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmTeacherMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmTeacherMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmTeacherMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnGet;
    private javax.swing.JButton btnRemove;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JMenuItem menuAddStudent;
    private javax.swing.JMenu menuCourses;
    private javax.swing.JMenuItem menuEnrolled;
    private javax.swing.JMenuItem menuGetAttendace;
    private javax.swing.JMenuItem menuGradeRecord;
    private javax.swing.JMenu menuLogOut;
    private javax.swing.JMenuItem menuManageCourses;
    private javax.swing.JMenuItem menuManageGrade;
    private javax.swing.JMenuItem menuRemoveStudent;
    private javax.swing.JMenuItem menuTakeAttendance;
    private javax.swing.JMenu menuTutorship;
    private javax.swing.JMenuItem menuTutorships;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
